<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerTiw0NEf\srcPiv_Guestbook_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerTiw0NEf/srcPiv_Guestbook_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerTiw0NEf.legacy');

    return;
}

if (!\class_exists(srcPiv_Guestbook_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerTiw0NEf\srcPiv_Guestbook_KernelDevDebugContainer::class, srcPiv_Guestbook_KernelDevDebugContainer::class, false);
}

return new \ContainerTiw0NEf\srcPiv_Guestbook_KernelDevDebugContainer([
    'container.build_hash' => 'Tiw0NEf',
    'container.build_id' => '092d8e21',
    'container.build_time' => 1571062687,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerTiw0NEf');
